name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Build JAR
        run: ./mvnw clean install

      - name: Build and Push Docker Image with Jib
        run: mvn compile jib:build -Dimage=registry.hub.docker.com/kpanchal11/google-jib-image-example
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
